version: "3.8"

services:
  db:
    image: mongo
    environment:
      - POSTGRES_USER=bruno
      - POSTGRES_PASSWORD=bruno
      - POSTGRES_DB=comicsdb
    volumes:
      - postgres_data:/var/lib/postgres/data/
    ports:
      - 5433:5432
   
  
volumes:
  postgres_data:   
