version: "3.8"

services:
  db:
    image: mongo
    ##build: ./mongodb/.
    container_name: mongodb
    command: [--auth]
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      NONGO_INITDB_DATABASE: comicsdb
    volumes:
      ##usuário vai precisar configurar
      - mongodbdata:/data/db
    ports:
      - "27018:27017"
    networks:
      - default-network

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8080
    environment:
      - COMICS_PUBLIC_KEY=e0756da495edd82c76b7fce7fde66520
      - COMICS_PRIVATE_KEY=b879fadc75fa7f1513d65797134ed8cb431b564d
    volumes:
      - mongodbdata:/data/db
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - default-network
   
  
volumes:
  mongodbdata:   

networks:
  default-network:
    driver: bridge
    
