# Generated by Django 3.2.9 on 2021-12-07 13:15

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=255)),
                ('description', models.TextField(default='')),
                ('attributionText', models.TextField(default='')),
                ('stories', djongo.models.fields.JSONField(default=[])),
                ('thumbnail', models.CharField(default='', max_length=500)),
            ],
            options={
                'db_table': 'character',
            },
        ),
    ]
