# Generated by Django 3.2.9 on 2021-12-04 02:19

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('comicsApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='id',
            new_name='_id',
        ),
        migrations.AddField(
            model_name='character',
            name='attributionText',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='character',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='character',
            name='stories',
            field=djongo.models.fields.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name='character',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
